# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(null=True)),
                ('domain', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'vk_group',
            },
        ),
        migrations.CreateModel(
            name='VkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('text', models.TextField()),
                ('likes_count', models.IntegerField()),
                ('reposts_count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
            ],
            options={
                'db_table': 'vk_post',
            },
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('photo_50', models.URLField(null=True)),
            ],
            options={
                'db_table': 'vk_user',
            },
        ),
        migrations.CreateModel(
            name='VkUserStatisticDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser')),
            ],
            options={
                'db_table': 'user_statistic_daily',
            },
        ),
        migrations.CreateModel(
            name='VkUserStatisticHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser')),
            ],
            options={
                'db_table': 'user_statistic_hourly',
            },
        ),
        migrations.CreateModel(
            name='VkUserStatisticTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser')),
            ],
            options={
                'db_table': 'user_statistic_total',
            },
        ),
        migrations.CreateModel(
            name='VkUserStatisticWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('week', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser')),
            ],
            options={
                'db_table': 'user_statistic_weekly',
            },
        ),
        migrations.AddField(
            model_name='vkpost',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='entities.VkUser'),
        ),
        migrations.AlterUniqueTogether(
            name='vkpost',
            unique_together=set([('group', 'post_id')]),
        ),
    ]
