# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 15:27
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_scheduled_task(*_):
    call_command('loaddata', 'entities/datafixtures/scheduled_task.json')
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_scheduled_task)
    ]
