# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_scheduled_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
