# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0002_auto_20161110_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuserstatisticdaily',
            name='likes_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticdaily',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticdaily',
            name='reposts_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistichourly',
            name='likes_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistichourly',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistichourly',
            name='reposts_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticperiod',
            name='likes_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticperiod',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticperiod',
            name='reposts_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistictotal',
            name='likes_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistictotal',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistictotal',
            name='reposts_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticweekly',
            name='likes_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticweekly',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticweekly',
            name='reposts_for_own_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(
                choices=[('rates.invites', 'rates.invites'), ('rates.likesForReposts', 'rates.likesForReposts'),
                         ('rates.reposts', 'rates.reposts'), ('rates.likes', 'rates.likes'),
                         ('period.duration', 'period.duration'), ('rates.repostsForReposts', 'rates.repostsForReposts'),
                         ('period.start', 'period.start')], max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(
                choices=[('rates.invites', 'rates.invites'), ('rates.likesForReposts', 'rates.likesForReposts'),
                         ('period.duration', 'period.duration'), ('rates.likesForOwnPosts', 'rates.likesForOwnPosts'),
                         ('rates.likes', 'rates.likes'), ('rates.repostsForReposts', 'rates.repostsForReposts'),
                         ('period.start', 'period.start'), ('rates.repostsForOwnPosts', 'rates.repostsForOwnPosts'),
                         ('rates.reposts', 'rates.reposts'), ('rates.ownPosts', 'rates.ownPosts')], max_length=100,
                primary_key=True, serialize=False),
        ),
    ]
