# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_vkgroup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuserstatistictotal',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
