# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_vkuserstatistictotal_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuserstatistictotal',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
