# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0006_vkrepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser',
                                           related_name='invited_with')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser',
                                                 related_name='invitations')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vk_invite',
                'unique_together': set([('user', 'group')])
            },
        ),
    ]
