# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_vk_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkgroup',
            name='vk_id',
            field=models.IntegerField(),
        ),
    ]
