# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_group_id_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuserstatisticdaily',
            name='invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistichourly',
            name='invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatistictotal',
            name='invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuserstatisticweekly',
            name='invites',
            field=models.IntegerField(default=0),
        ),
    ]
