# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_invites_in_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'run_period',
            },
        ),
        migrations.CreateModel(
            name='VkUserStatisticPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('likes_for_reposts', models.IntegerField(default=0)),
                ('reposts_for_reposts', models.IntegerField(default=0)),
                ('invites', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkGroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.RunPeriod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VkUser')),
            ],
            options={
                'db_table': 'user_statistic_period',
            },
        ),
    ]
