# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_runperiod_vkuserstatisticperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(choices=[('period.start', 'period.start'), ('period.duration', 'period.duration'), ('rates.likes', 'rates.likes'), ('rates.likesForReposts', 'rates.likesForReposts'), ('rates.repostsForReposts', 'rates.repostsForReposts'), ('rates.reposts', 'rates.reposts'), ('rates.invites', 'rates.invites')], max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
